---
- name: "Bastion : Create {{ wg_routing_mesh_group }}/{{ wg_key_path }}"
  file:
    mode: '0700'
    path: "{{ bastion_key_path }}/{{ wg_key_path }}"
    state: 'directory'
  become: true

- name: "Bastion : Generate Private and Public Keys"
  shell:
    cmd: wg genkey | tee privatekey | wg pubkey > publickey
    creates: "{{ bastion_key_path }}/{{ wg_key_path }}/publickey"
  args:
    chdir: "{{ bastion_key_path }}/{{ wg_key_path }}"
  no_log: "{{ wg_routing_hide_private_key }}"
  become: true
